
server:
  tomcat:
    accesslog:
      enabled: true
  port: 9003

spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/prueba_nequi
    username: danielao
    password: pruebanequi.
    pool:
      initial-size: 5
      max-size: 20
      enabled: true

